### PR TITLE
Damage from falling into leaves now uses fall damage (DamageSource.FALL)

### PR DESCRIPTION
**Pull request by Laike-Endaril**
This provides compat with all forms of fall damage alteration from MC and from other mods.

### CODE REVIEW

**Comment by Laike-Endaril** [comment]
Fixes #23

**Comment by srs-bsns** [comment]
This PR is targetting the wrong branch. New PRs should be targetting `1.12-final`, which is the latest branch with the most updated code. However, due to the changes that have been made from the `1.12` branch to the `1.12-final` branch (the functionality you are changing was moved), this PR can not be retargetted.

Regardless, this change will not be accepted for the fallowing reasons:

1. Passable Leaves' custom damage source is just that, a custom damage source that was meant to be unique. It was created to reflect that this damage is added for a new mechanic that does not exist in the vanilla game (passing through specific non-solid blocks). It is not an alternative fall damage (into a solid block). Furthermore, you removed the damage reduction if the entity has the jump boost potion effect, which is a vanilla mechanic that should have remained as part of the damage calculation.

2. This is not a Passable Leaves issue.
If a mod adds an entity that should be impervious to fall damage, then that mod should prevent what triggers the damage to be applied instead of allowing it and then intervening at the moment the damage is being added. That is, in the places where `Entity.fallDistance` is updated, it should be modified to such a value so that when that entity comes into contact with a block (solid, or otherwise) the game will not make the determination that the entity has fallen a great distance, and therefore not attempt to apply fall damage at all. This will also affect Passable Leaves, as it's damage is applied based on the `fallDistance`.


In the case of Ice and Fire, the entity is also rideable, so there should also be care in making sure that the `fallDistance` of the rider is also reset.

My suggestion is that you contact the authors of Ice and Fire and see if they are willing to change how they handle the flying/falling of their flying entities.

**Comment by Laike-Endaril** [comment]
Sorry about the branch issue, somehow I missed that.

1a. To me, it makes more sense to use fall damage simply because you're still triggering damage due to falling (even if the collision does not completely stop you).

1b. I'm fairly certain the jump boost damage reduction would have been calculated twice if I had left it there, but I could be wrong.  I'll have to double check that, as I, at least, will be using my version of the mod.

2. The "accepted" way of altering fall damage is to catch the LivingHurtEvent, especially since any mod adding a potion effect or other mechanic will not be altering entities directly.  This issue is far easier to solve within Passable Leaves than in every other mod made for MC.

But in the end, it is not my mod, so if you still don't want the change, I will not argue any further ;)

**Comment by srs-bsns** [comment]
> I'm fairly certain the jump boost damage reduction would have been calculated twice

No, because the damage is being applied manually and the `fallDistance` is reset before the game determines if fall damage should be applied. If this weren't the case then fall damage would also be applied on top of our custom damage.

> The "accepted" way of altering fall damage is to catch the LivingHurtEvent

Events such as that exist to expose internal functionality so that mods have access to modify the basic bahaviour of the game which they normally do not have access to.

For example, if I add a block to prevent entities from taking fire damage when standing on it, I might want to use the `LivingHurtEvent` to prevent chickens from taking damage, since chickens are added by vanilla and can't have their functionality modified without using ASM.

With respect to #23, this is not the case. If a mod adds an entity, they have full access to the class and can override any functionality within its class inheritence. And as I said in my previous comment, the best case here is to prevent the event from even occuring instead of attempting to override the result of the event.

Furthermore, although events like this give a great deal of access to internal behaviour, they still have their weaknesses, such as being highly susceptible to race conditions as other mods may act on the event first with undesireable results. For instance, I could create a mod with a higher priority event listener to kill all entities from fall damage before other mods can prevent it, which is all the more reason to force desireable functionality through method overrides.

**Pull request closed without merging**
